Feature/dcc 5774 dcc repository investigate indexing song supported repositories
icgc-dcc/dcc-repository pull request #8
Opened 2017-08-11 21:03 UTC by KevinFHartmann

This is ready for a PR, assuming that the output is what we want it to be. :-)

It looks pretty good to me, but I might have missed/misunderstood something, so it would probably be good to have someone else review it, too. :-)

2017-08-14 15:16 UTC, andricDu requested changes
I've noticed some of the files are using 4 spaces for indentation. Lets bring them back to 2 for consistency with the rest of our code base. 

Once you set the default in IntelliJ you can just use the IDE to reformat.

2017-08-14 15:16 UTC, andricDu commented on dcc-repository-song/src/main/java/org/icgc/dcc/repository/song/core/SongProcessor.java
> +        return StreamSupport.stream(analyses.spliterator(), false).
Method reference and static imports

```java
        return stream(analyses.spliterator(), false).
                flatMap(this::convertFiles).collect(toList());
```

2017-08-14 15:16 UTC, andricDu commented on dcc-repository-song/src/main/java/org/icgc/dcc/repository/song/core/SongProcessor.java
> +        for(val file: analysis.getFiles()) {
This whole method could be shortened down to:

```java
        return analysis.getFiles().stream()
            .filter(f -> !isIndexFile(f.get(fileName)))
            .map(f -> convert(f, analysis));
```

2017-08-24 17:02 UTC, KevinFHartmann commented
This is ready to be reviewed again. :-)

2017-12-11 16:55 UTC, andricDu approved these changes

2017-12-11 16:58 UTC, andricDu requested changes

2017-12-11 16:58 UTC, andricDu commented on dcc-repository-core/src/main/java/org/icgc/dcc/repository/core/util/RepositoryFiles.java
> +    if (fileCopy == null) {
fileCopy cannot be null due to the `@NonNull`

2017-12-11 18:51 UTC, andricDu approved these changes

2017-12-11 18:51 UTC, merged